spring:
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name: org.postgresql.Driver
  application:
    name: idolSpring
graphql:
  spqr:
    gui:
      enabled: true
